grpc:
  client:
    blog-service:
      address: 'static://127.0.0.1:9091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
graphql:
  servlet:
    exception-handlers-enabled: true
